### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by VB10** [yunus6116/YAYA#15]
elinize sağlık

- türkçe ingilzce karışmış tek yapmlısnı
- function veya widgetlar sınıfların içinde olmaı
- theme dosyanız olmalı
- constlarınız ile static fileları yonetmeilsiniz
- sayfalarınza viewmodel viewcontrolelr sınfıları yazarak viewdan işleri allmasınız
-

**Comment by yunus6116** [comment]
Ekip olarak değerli yorumlarınızı dikkate alıp bir sonraki projemizde uygulamak için sabırsızlanıyoruz. Bizi bir sonraki seviyeye çıkartacak bu yorumlarınız için ben ve ekibim adına çok teşekkür ederim. vb is life :)
